# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Acta.create([
  { :ciudad => nil, :fecha => nil, :hora_inicio => nil, :hora_terminacion => nil, :lugar => nil, :tema => nil, :objetivo_de_la_reunion => nil, :desarrollo_reunion => nil, :conclusiones => nil, :firmas => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Asignacioncomite.create([
  { :nombres => nil, :apellidos => nil, :programa => nil, :ficha => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Ayuda.create([
  { :nombre => nil, :created_at => nil, :updated_at => nil, :archivo_file_name => nil, :archivo_content_type => nil, :archivo_file_size => nil, :archivo_updated_at => nil }
], :without_protection => true )



Cargo.create([
  { :descripcion => "Aprendiz", :created_at => "2013-12-02 19:14:13", :updated_at => "2013-12-02 19:14:13" },
  { :descripcion => "Instructor ", :created_at => "2013-12-02 19:14:32", :updated_at => "2013-12-02 19:14:32" }
], :without_protection => true )



Centro.create([
  { :nombre => "Centro de Formacion en Diseño, Confeccion y Moda", :abreviatura => "CFDCM", :created_at => "2013-12-02 18:58:45", :updated_at => "2013-12-02 18:58:45" }
], :without_protection => true )



Comite.create([
  { :hora => nil, :nombreapren => nil, :programa_id => nil, :ficha => nil, :fcomite_id => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Coordinador.create([
  { :nombre => "camilo", :email => "chrystiamgg@misena.edu.co", :created_at => "2013-12-02 19:08:15", :updated_at => "2013-12-02 19:08:15" }
], :without_protection => true )



Estado.create([
  { :nombre => "en espera ", :descripcion => "la queja fue creada y espera a ser enviada a comite ", :created_at => "2013-12-02 19:50:45", :updated_at => "2013-12-02 19:50:45" },
  { :nombre => "remitido a comite", :descripcion => "la queja fue remitida a comite", :created_at => "2013-12-02 19:53:25", :updated_at => "2013-12-02 19:53:25" }
], :without_protection => true )



Falta.create([
  { :falta => "Academica", :descripcion => "no cumple con los trabajos", :created_at => "2013-12-02 18:46:54", :updated_at => "2013-12-02 18:46:54" },
  { :falta => "Diciplinaria", :descripcion => "ofender a un instructor", :created_at => "2013-12-02 18:47:54", :updated_at => "2013-12-02 18:47:54" }
], :without_protection => true )



Fcomite.create([
  { :fecha => nil, :lugar => nil, :tipo => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Funcionario.create([
  { :nombres => nil, :apellidos => nil, :cedula => nil, :email => nil, :direccion => nil, :telefono => nil, :fch_nacimiento => nil, :cargo => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Instructor.create([
  { :nombres => nil, :apellidos => nil, :cedula => nil, :email => nil, :direccion => nil, :telefono => nil, :fch_nacimiento => nil, :modalidad => nil, :created_at => nil, :updated_at => nil, :imagen_file_name => nil, :imagen_content_type => nil, :imagen_file_size => nil, :imagen_updated_at => nil }
], :without_protection => true )



Prioridad.create([
  { :nombre => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Programa.create([
  { :descripcion => "analisis y  de desarrollo  de sistemas de informacion", :abreviatura => "ADSI", :coordinadora_id => nil, :centro_id => 1, :created_at => "2013-12-02 19:02:14", :updated_at => "2013-12-02 19:02:14", :estado => true }
], :without_protection => true )



Role.create([
  { :name => "admin", :created_at => "2013-12-02 16:44:24", :updated_at => "2013-12-02 16:44:24" }
], :without_protection => true )



TipoDocumento.create([
  { :sigla => "CC", :descripcion => "Cedula", :created_at => "2013-12-02 18:45:35", :updated_at => "2013-12-02 18:45:35" }
], :without_protection => true )



User.create([
  { :username => "camilo", :email => "camilo@hotmail.com", :crypted_password => "$2a$10$SFhHxfzukK2k1J.LWowbDeqp6bcI4Zbc6arIu3IKWOIzu6TuIUPpy", :salt => "mBJ2FWsqUepVyTkYrZ7N", :created_at => "2013-12-02 18:20:38", :updated_at => "2013-12-02 18:20:38", :remember_me_token => nil, :remember_me_token_expires_at => nil, :nombre => "camilo" }
], :without_protection => true )



UserRole.create([
  { :user_id => 1, :role_id => 1, :created_at => "2013-12-02 18:20:38", :updated_at => "2013-12-02 18:20:38" }
], :without_protection => true )



Usercomite.create([
  { :nombre => nil, :email => nil, :comite_id => nil, :cargo_id => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )


